{
    'name': 'Ichhapurti Customisations',
    'version': '14.0.4.1.0',
    'description': """""",
    'summary': 'Ichhapurti Customisations',
    'category': 'tools',
    'author': 'Cybrosys Technologies',
    'depends': ['base', 'stock', 'contacts', 'sale_management', 'product_enhancement'],
    'data': [
        'views/login.xml',
        'views/resupply_route.xml',
        # 'views/res_company.xml',
        'views/sale_order.xml',
        'views/stock_move.xml',
        # 'views/wizard.xml',
        'views/res_users.xml',
        'views/stock_warehouse.xml',
        'security/ir.model.access.csv',
        # 'security/record_rule_warehouse_user.xml',
    ],
    'demo': [],
    'installable': True,
    'application': False,
    'auto_install': False,
}
